# -*- coding: utf-8 -*-
"""MCU Quiz Game.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1wKgQFY7mu6bQp6q9g4sZJPFszTKXFQoA
"""

# ------------------------------------------------------------
 def new_game():
   guesses = []
   correct_guess = 0
   qNum = 1

   for key in question:
     print("--------------------MCU QUIZ-----------------------")
     print(key)
     for i in option[qNum-1]:
       print(i)
     guess = input("Choose an option (A, B, C or D): ").upper()
     guesses.append(guess)
     correct_guess += check_answer(question.get(key), guess)
     qNum += 1

   score(correct_guess, guesses)

# ------------------------------------------------------------
def check_answer(answer, guess):
  if answer == guess:
    print("Correct answer!")
    return 1
  else:
    print("Wrong answer!")
    return 0

# ------------------------------------------------------------
def score(correct_guess, guesses):
  print("-----------------------------------------------------")
  print("--------------::::::::RESULTS::::::::----------------")
  print("-----------------------------------------------------")

  print("Correct Answers: ",end=" ")
  for i in question:
    print(question.get(i), end=" ")
  print()

  print("Your Answers:    ",end=" ")
  for i in guesses:
    print(i, end=" ")
  print()

  score = int((correct_guess/len(question))*100)
  print("Your score is "+str(score)+"%")
   
# ------------------------------------------------------------
def play_again():
  response = input("Do you want to play again? (YES or NO): ").upper()

  if response == "YES":
    return 1
  else:
    return 0

# ------------------------------------------------------------
# PROGRAM STARTS FROM HERE
# question IS A LIST HOLDING QUESTION AS KEY AND ANSWER AS VALUE
question = {
    "1. What year was the first Iron Man movie released":"C",
    "2. What is the name of Thor’s hammer?" :"B",
    "3. The Flerkens are a race of extremely dangerous aliens that resembles what?":"A",
    "4. Who is the father of the Black Panther?": "C",
    "5. What is the alien race Loki sends to invade Earth in The Avengers?": "A",
    "6. Who killed Tony Stark’s parents?":"D",
    "7. What is the only Marvel film not to have a post-credit scene?":"D",
    "8. In which film’s post-credit scene did Thanos first appear?": "D",
    "9. Who killed Thor's mother?" : "B",
    "10. Which Infinity Stone was first collected by Thanos in Endgame?" : "C"
}

# option IS THE LIST OF MCQ OPTIONS
option = [
          ["A. 2005", "B. 2006", "C. 2008", "D. 2010"],
          ["A. Stormbreaker", "B. Mjolnir", "C. Meow Meow", "D. Djornbern"],
          ["A. cat", "B. dog", "C. Kree", "D. skrull"],
          ["A. N'Jadaka","B. N'Jobu", "C. T'Chaka", "D. T'Challa"],
          ["A. Chitauri","B. Skrulls","C. Flerkens","D. Kree"],
          ["A. Mandarin","B. HYDRA","C. Loki","D. Winter Soldier"],
          ["A. Hulk","B. Iron Man 3","C. GOTG 2","D. Endgame"],
          ["A. Iron Man 2","B. GOTG 2","C. Avengers","D. Age of Ultron"],
          ["A. Malekith","B. Kurse","C. Dark Elves","D. Destroyer"],
          ["A. Space","B. Reality","C. Power","D. Soul "]
]
# ------------------------------------------------------------
new_game()


while play_again():
  new_game()

print("----------!!!!!GAME OVER!!!!!----------")