# -*- coding: utf-8 -*-
"""rock paper scissors.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1m1hvej_Okk6c-_x8xDDnAxRd6HCNyBfT
"""

# ROCK-PAPER-SCISSORS GAME
import random

option = ["rock","paper","scissors"]
round = int(input("Enter the number of Rounds: "))
# points initialization
c=p=0

for i in range(round):
  computer = random.choice(option)
  player = None
  while not player in option:
    player = input("Rock, Paper or Scissors???")

  if player == computer:
    print("Tie!!!")
  elif player == "rock":
    if computer == "paper":
      print("Computer: "+computer)
      print("Player: "+player)
      print("Computer Wins")
      c = c + 1
    else:
      print("Computer: "+computer)
      print("Player: "+player)
      print("Player Wins")
      p = p + 1
  elif player == "paper":
    if computer == "rock":
      print("Computer: "+computer)
      print("Player: "+player)
      print("Player Wins")
      p = p + 1
    else:
      print("Computer: "+computer)
      print("Player: "+player)
      print("Computer Wins")
      c = c + 1
  elif player == "scissors":
    if computer == "rock":
      print("Computer: "+computer)
      print("Player: "+player)
      print("Computer Wins")
      c = c + 1
    else:
      print("Computer: "+computer)
      print("Player: "+player)
      print("Player Wins")
      p = p + 1

if c>p:
  print("Computer wins the game!!!")
elif p>c:
  print("Player wins the game!!!")
else:
  print("---Match Draw---")